name: 'gatsby-fastly-purge-action'
description: 'Purge Gatsby public HTML and JSON files cached by Fastly'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  fastly-token:
    description: Token used to call the Fastly purge API
    required: true
  fastly-url:
    description: Fastly base URL
    required: true
